- type: job
  id: StalkerRene
  name: job-renegade
  icon: rene
  description: job-renegade-desc
  playTimeTracker: JobRenegat
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobRenegat
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: ReneGear
  supervisors: job-renegade-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Renegat
        - type: Bands
          band: Stalker
          bandIcon: rene
          bandProto: STRenegatsBand
          bandRankId: 1
        - type: BlockTackingHolyItems

- type: job
  id: StalkerHeadRene
  name: Renegade Leader
  icon: rene
  description: Protect Flesh. Take Teeth.
  playTimeTracker: JobHeadRenegat
  whitelisted: true
  requirements:
  # - !type:RoleTimeRequirement
  #   role: JobRenegat
  #   time: 1
  - !type:SpeciesRequirement
    species:
    - Human
    - Dwarf
  startingGear: ReneGear
  supervisors: you're the boss.
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
    - type: Access
      tags:
      - Renegat
    - type: Bands
      band: Stalker
      bandIcon: rene
      bandProto: STRenegatsBand
      bandRankId: 2
    - type: BlockTackingHolyItems

- type: startingGear
  id: ReneGear
  equipment:
    id: BandPDA
    head: ClothingHeadHatGreyFlatcap
    torso: ClothingTorsoTShirtColorBlack
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
    back: ClothingBackpackDuffelBlackStalker
- type: stBand
  id: STRenegatsBand
  name: Renegades
  factionId: Renegades
  maxMembers: 12
  managingRankId: 2
  hierarchy:
    1: StalkerRene
    2: StalkerHeadRene
